### ISSUE TITLE
Really would love this to work. 

### ISSUE THREAD

**Issue by intenebrisbyjs167** [Jamminroot/intag#1]
But it's triggering Norton with a malicious file in my Google Chrome user data..? And the original .exe is greyed out, saying I need permission from myself to edit the file.

I really just needed this to organize my freelance project folders. Bit worried now. The interface in your screenshots were really perfect for what I need it for.

**Comment by Jamminroot** [comment]
That's odd... I'll check it out by the end of the day

**Comment by Jamminroot** [comment]
Hey! I've re-assembled exe now. Can you check if that works for you? I don't mind fixing the issue, but I can't really see the problem. Optionally you can hit me up on discord or telegram, and we'd be able to see what's wrong with the tool.

Otherwise, I can only suggest compiling from source locally :(

ps sorry for a delay :D

**Comment by Jamminroot** [comment]
https://github.com/Jamminroot/intag/releases/tag/1.0.2.1

**Comment by Jamminroot** [comment]
I've made a few changes to how this works, check out latest version Intag 1.0.3.0-a

**Comment by Jamminroot** [comment]
Closing issue for now, but feel free to reopen just in case

**Comment by intenebrisbyjs167** [comment]
Hey, thanks, got it. No warning anymore. But how do I install? Through CMD prompt? opening the .exe does nothing. Is it a permissions issue?

**Comment by Jamminroot** [comment]
Glad to hear that :)

I believe it should be an elevated command prompt as it edits registry. So yeah, run with CMD admin rights, locate to where you copied executable to, and type `intag.exe install` there.

Second option is to save this to a `*.reg` file and double-click it:
>**NOTE** You'd have to change `C:\\<PUT YOUR PATH HERE>` to the your folder.
```reg
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\Folder\shell\InTag\command]
@="C:\\<PUT YOUR PATH HERE>\\intag.exe %1"
```

Other option is to manually edit registry with run > `regedit` (similar to the above method, but all done manually).

Details on those should be in ./readme.md
