### ISSUE TITLE
Suggestion: multiple folder tagging

### ISSUE THREAD

**Issue by CNSabata** [Jamminroot/intag#11]
Hello. Big fan of your app. 
Do you think it could possible to add a regedit entry/make it so it can intake multiple folders at once ?
I'm trying to manage a huge clutter of these and I haven't found an option for that.
I tried to iterate on my selection, but logically even if I fed 70 folders to the soft, I will end up with 70 windows opened.

Cheers and keep up the good work 😃

**Comment by Jamminroot** [comment]
Hey hey! Appreciate your interest :)

I'll have a look at it by the weekend, not getting much free time lately.

If you have an Idea how that'd be handy to be implemented - feedback is very welcome. For now, I see it as triple-state buttons (active-for-all, inactive, active-for-some) in case tags dont match... Or even just 2 states, with "*" on a button?..

Need to give it a thought.

**Comment by Jamminroot** [comment]
Shouldn't be too hard. If I dont stumble on something which would require a lot of time - I'll add plain "assign new" feature to a set of folders. As for states - right after that, not sure when though.

**Comment by CNSabata** [comment]
Thanks for the quick response by the way, I hadn't noticed your comment and started working my day like usual haha. It's great to see a barebone simple project like this one answer a feature I've been craving for a long time now, and have very quick response to a suggestion I gave as a night thought not even 24 hours ago haha

**Comment by Jamminroot** [comment]
Well I somewhat care about what I do :D

And what I meant is how that'd look on the outside. From the inside - yeah, plain approach would be to allow app to accept multiple folders, which shouldn't be this hard... I think :D

**Comment by Jamminroot** [comment]
@CNSabata lmk if its working

**Comment by CNSabata** [comment]
Hey, sorry I forgot to test it, got busy with work and it kind of stepped into my last weekends too.
I tried it, but selecting multiple folders have the same behavior as before, with multiple executions of intag.exe, and when I click and apply a tag only one folder gets it.
Hope that can help

**Comment by Jamminroot** [comment]
That is odd. I'll check the version I uploaded once I can

**Comment by Jamminroot** [comment]
Maybe you've forgot to update registry entry? Just double-clicking the app is enough for that.

Meanwhile, I'll polish the app and make a realease

**Comment by Jamminroot** [comment]
https://github.com/Jamminroot/intag/releases/tag/1.4.0.0

Finished version released. 

![image](https://user-images.githubusercontent.com/6387654/201477341-f68a873f-545d-4226-b058-787cbb56a544.png)

Closing the issue, feel free to open a new one if smth is wrong
