### ISSUE TITLE
Prompts UAC every time when run

### ISSUE THREAD

**Issue by OLCadlywydd** [Jamminroot/intag#12]
UAC is prompted every time I tag a file. I understand that administrator permissions are required on the initial run to set up the registry keys, but it should not be required simply to tag a folder/file. Could a separate install .exe be provided perhaps, so that UAC is only prompted during install?

**Comment by Jamminroot** [comment]
I'll have a look on how to resolve it by the weekend

**Comment by Jamminroot** [comment]
That's not something I'd implement at the moment, as resolving windows smart screen and UAC prompts would require signing of applications.
And since I'm not developing my own pet-projects at capacity which would allow to cover expenses for certificates (lowest is ~200 USD per year), I'm afraid that this is not something I'd currently resolve. The only solution (which I wouldn't really recommend, tbh) is to lower UAC security level.

**Comment by OLCadlywydd** [comment]
Please don't apologise! This tool is really handy, it's just a minor thing really. Obtaining a certificate for a small project like this would be a bit ridiculous anyway haha.

I did find that you can force an application to run without admin by adding a Registry entry under "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers". Just add a key with the name as the exe's path, and the value as "~ RunAsInvoker":
![image](https://user-images.githubusercontent.com/72607789/212062978-c961fd11-31e4-46f9-87a0-efa48536ace2.png)

I've tested it and the exe now runs without an admin prompt but all tagging functionality still works fine.

Can the key just be added to AddToContextMenu.reg? I know admin perms are required initially for registry modification, but is there anything else that requires admin afterwards?

**Comment by Jamminroot** [comment]
I believe that might be a solution - given that no system folders are to be changed. I'll give it some more thought by the end of the week

**Comment by Jamminroot** [comment]
Ok I think I got this without code signing. Thanks for pointing out a direction.

The only downside I can see - trying to tag system\protected folders. Aside from that - It should work, given the user has admin rights.

Have a look at latest release, and let me know if something's not working for you.

https://github.com/Jamminroot/intag/releases/tag/1.4.1.0

I'll close the issue for now.
