### ISSUE TITLE
Fixes and improvements

### ISSUE THREAD

**Issue by montoner0** [Jamminroot/intag#19]
Hi,

I've made a number of fixes and improvements to the app such as:
1. Close the form on Enter if the tag input field is empty
2. Throw exceptions if registering the extension fails
3. Show a message to a user when the app fails (currently you can only guess if something went wrong)
4. Add support for more than 15 selected items in Explorer
5. Fix issues with an interprocess communication for multiselection (the current implementation is unreliable, sometime it works, sometime don't)
6. Added a message when no valid files/folders are passed to a command line
7. Automatically elevate a process during (un)installation if needed
8. Tags sorting (tags are sorted in alphabetical order both in UI and when saved)

Please let me know if you're interested in these changes, I'll make a PR.

**Comment by Jamminroot** [comment]
Hello!
That sounds amazing, please, do open the PR, I'd be happy to provide those to general public
