### ISSUE TITLE
Where is .exe?

### ISSUE THREAD

**Issue by dorbitbrown** [Jamminroot/intag#2]
My understanding from the readme is that we need to run some xxx.exe --install.  Is that correct?

Cloned the repo, then did a *.exe search, but can't find anything.  Is it missing, or am I just making a newbie mistake?

**Comment by Jamminroot** [comment]
Hey! Repo is sources container with history, while exe is a binary artifact. You can find exe on releases page:
https://github.com/Jamminroot/intag/releases/tag/1.0.2.1

**Comment by Jamminroot** [comment]
... and as for argument, it's just `install`: `C:\tools\intag.exe install`

**Comment by dorbitbrown** [comment]
Thank you!
