### ISSUE TITLE
Problem with UTF-16 LE encoding

### ISSUE THREAD

**Issue by aidybnt** [Jamminroot/intag#8]
![Snipaste_2022-02-16_16-34-39](https://user-images.githubusercontent.com/7421456/154226196-9a7b2c24-9722-4c5f-87d1-62e0fe13b62d.png)

Thank you very much help me.

Before, i modify desktop.ini, and save as UTF16 LE，messy code is none.

please,help,thank you very much.

I like intag very much ,please fix it . please thank you very much.

![Snipaste_2022-02-16_16-44-12](https://user-images.githubusercontent.com/7421456/154227740-904bee13-ce74-422d-b519-8dfe28d2b746.png)

**Comment by Jamminroot** [comment]
Hey! Thanks for letting me know about this. I'll have a look at this as soon as I get some free time

**Comment by Jamminroot** [comment]
Hey again, would you mind sharing a sample Desktop.ini file so that I can test it?

**Comment by Jamminroot** [comment]
[intag.zip](https://github.com/Jamminroot/intag/files/8091991/intag.zip)
I didn't really get to test it much as my VSCode\OS struggles with UTF-16 LE encoding, but I hope this version should do the trick for you. 
If that's ok with you - can you check and let me know if the issue is fixed, so that I can update published version?

**Comment by aidybnt** [comment]
[Desktop.zip](https://github.com/Jamminroot/intag/files/8101739/Desktop.zip)
![Snipaste_2022-02-19_16-49-34](https://user-images.githubusercontent.com/7421456/154793893-efb68897-b3d7-4b61-b2d4-0b8f2510373e.png)

This is desktop file

Thank you very muck

**Comment by Jamminroot** [comment]
Yup, it is reproduced on my side (I think).
![image](https://user-images.githubusercontent.com/6387654/154796371-3cb3b53a-6c94-4783-9098-a24f6f88b1c7.png)
I'll have a look at what I can do this weekend

**Comment by Jamminroot** [comment]
I think I got this working.
I'll push update in a few minutes

**Comment by Jamminroot** [comment]
If the problem is not resolved - reopen the issue, please

**Comment by aidybnt** [comment]
The problem was solved perfectly.
Thank you very much!!!
Thank you very much!!!
Thank you very much!!!

:clap::clap::clap:

**Comment by Jamminroot** [comment]
My pleasure! Enjoy :)
