### ISSUE TITLE
Individual files support

### ISSUE THREAD

**Issue by Taemaly** [Jamminroot/intag#9]
Question ,is there any way to may intag work for individual files and not folders.I know ther eis a way to add tags by foing into properties and then add tag to details but I find htat too time consuming and was wondering if its possible to implement intagg feature to work for individual files also?

**Comment by Jamminroot** [comment]
Short answer: at current state, no.
Loner one: It's not going to work as it is even if I allow applying that to separate files as it tries to look at Desktop.ini "inside" file(?). Even more so, It will just crash.
That said, some files have designated metadata fields in them, which windows explorer can work with:
![image](https://user-images.githubusercontent.com/6387654/182619339-3ef310c2-c1b7-4bb6-9c84-a4c07d4f3ceb.png)
And that can actually be addressed.
I'll check what can be done in that direction. Not giving any promises, but I think that would be a good addition.

For now I plan to look at `jpeg` and `jpg` extensions. If you can provide other file extensions which do support tags natively, please let me know.
Ill come back by the weekend with smth specific.

**Comment by Jamminroot** [comment]
Also, sorry for a delay - was away.

**Comment by Jamminroot** [comment]
Okay I've looked at it.
Good news is: that's doable:
![image](https://user-images.githubusercontent.com/6387654/183139306-91334c7a-41e0-43b5-b8da-d57fa1dd6486.png)
Bad news is that current way to implement that would require me to use additional libraries (extra files alongside `.exe` of the application), which I'm not quite happy about as one of the initial criterias was "single-file-executable" (aka lightweight).

I'll have a look at what can be done with that.

**Comment by Jamminroot** [comment]
Have a look at this assymbly. It is barely polished, and might (and probably would) contain a lot of errors.

I am still not sure if I'm going to go with what I did, since that is not smth to be proud of (code-wise), but might solve your issue.

[intag.zip](https://github.com/Jamminroot/intag/files/9274074/intag.zip)

Also, check out sidebar; Not sure about W10\W7, but W11 has this:
![image](https://user-images.githubusercontent.com/6387654/183225956-364c070f-c247-4474-9433-a66e0263bc23.png)

**Comment by Jamminroot** [comment]
Pushing new release now

**Comment by Jamminroot** [comment]
https://github.com/Jamminroot/intag/releases/tag/1.3.0.0
